apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-nginx-deployment
  labels:
    app: argo-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-nginx
  template:
    metadata:
      labels:
        app: argo-nginx
    spec:
      containers:
        - name: nginx
          image: "__IMAGE_URL__" # CI에서 자동으로 업데이트됩니다.
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: argo-nginx-svc
  labels:
    app: argo-nginx
spec:
  type: ClusterIP
  selector:
    app: argo-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/group.name: argo-nginx-ingress-group
  labels:
    app: argo-nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-nginx-svc
                port:
                  number: 80
